<a href="https://colab.research.google.com/github/SarwatMustafa-03/data-analysis-with-python/blob/main/WorkForce__Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.read_csv("employee_data_raw.csv")

df.head()
print(df.shape)
print(df.columns)

(32, 6)
Index(['Employee_ID', 'Employee_Name', 'City', 'Department', 'Salary',
       'Joining_Year'],
      dtype='object')

In [ ]:
df.head()
df.shape
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Employee_ID    32 non-null     int64
 1   Employee_Name  32 non-null     object
 2   City           32 non-null     object
 3   Department     32 non-null     object
 4   Salary         32 non-null     int64
 5   Joining_Year   32 non-null     int64
dtypes: int64(3), object(3)
memory usage: 1.6+ KB

       Employee_ID       Salary  Joining_Year
count    32.000000     32.00000     32.000000
mean   1015.281250  60312.50000   2020.468750
std       8.692727  12387.39604      2.475485
min    1001.000000  42000.00000   2017.000000
25%    1007.750000  49500.00000   2018.000000
50%    1015.500000  59000.00000   2020.500000
75%    1022.250000  70000.00000   2022.000000
max    1030.000000  80000.00000   2025.000000

In [ ]:
import pandas as pd

df = pd.read_csv("employee_data_raw.csv")
df["Employee_Name"] = df["Employee_Name"].str.strip().str.title()
print(df["Employee_Name"])

0          Ali Khan
1        Sara Ahmed
2         Ahmed Ali
3       Ayesha Khan
4       Hassan Raza
5       Fatima Noor
6       Usman Tariq
7      Zainab Malik
8       Bilal Ahmed
9         Hira Shah
10      Omar Farooq
11       Sana Iqbal
12       Hamza Khan
13       Maryam Ali
14      Danish Raza
15       Iqra Ahmed
16      Saad Hassan
17        Maha Khan
18      Talha Malik
19       Nimra Shah
20        Fahad Ali
21       Komal Raza
22        Asad Khan
23       Laiba Noor
24      Rehan Ahmed
25       Anum Tariq
26    Shahzaib Khan
27         Eman Ali
28       Arham Raza
29     Areeba Malik
30      Fatima Noor
31        Maha Khan
Name: Employee_Name, dtype: object

In [ ]:
import pandas as pd
df=pd.read_csv("employee_data_raw.csv")
df["City"]=df["City"].str.strip().str.title()
print(df["City"])

0        Karachi
1        Karachi
2         Lahore
3         Lahore
4      Islamabad
5      Islamabad
6     Rawalpindi
7     Rawalpindi
8        Karachi
9        Karachi
10        Lahore
11        Lahore
12     Islamabad
13     Islamabad
14    Rawalpindi
15    Rawalpindi
16       Karachi
17       Karachi
18        Lahore
19        Lahore
20     Islamabad
21     Islamabad
22    Rawalpindi
23    Rawalpindi
24       Karachi
25       Karachi
26        Lahore
27        Lahore
28     Islamabad
29     Islamabad
30     Islamabad
31       Karachi
Name: City, dtype: object

In [ ]:
import pandas as pd
df=pd.read_csv("employee_data_raw.csv")
df["Department"]=df["Department"].str.strip().str.title()
print(df["Department"])

0        Finance
1        Finance
2             Hr
3             Hr
4             It
5             It
6      Marketing
7      Marketing
8     Operations
9     Operations
10       Finance
11       Finance
12            Hr
13            Hr
14            It
15            It
16     Marketing
17     Marketing
18    Operations
19    Operations
20       Finance
21       Finance
22            Hr
23            Hr
24            It
25            It
26     Marketing
27     Marketing
28    Operations
29    Operations
30            It
31     Marketing
Name: Department, dtype: object

In [ ]:
import pandas as pd
df=pd.read_csv("employee_data_raw.csv")
print(df.duplicated().sum())

2

##FILTERRRRRRRRRRRRRRRRR

In [ ]:
df["City"] = df["City"].str.strip().str.title()
kar_emp = df[df["City"] == "Karachi"]
print(kar_emp)
kar_emp.to_csv("employee_data_raw.csv", index=False)

    Employee_ID  Employee_Name     City    Department  Salary  Joining_Year
0          1001      ali khan   Karachi       Finance   70000          2018
1          1002     Sara Ahmed  Karachi       finance   42000          2021
8          1009    Bilal Ahmed  Karachi    Operations   50000          2025
9          1010      Hira Shah  Karachi   operations    65000          2017
16         1017    Saad Hassan  Karachi     Marketing   75000          2023
17         1018      Maha Khan  Karachi     marketing   55000          2021
24         1025    Rehan Ahmed  Karachi            IT   80000          2017
25         1026     Anum Tariq  Karachi            it   75000          2024
31         1018      Maha Khan  Karachi     marketing   55000          2021

In [ ]:
df = pd.read_csv("employee_data_raw.csv")
filtered_employees_df = df[df["Salary"] >= 60000]
print(filtered_employees_df["Salary"])

0    70000
3    65000
4    75000
6    80000
7    75000
Name: Salary, dtype: int64

In [ ]:

df["Department"]=df["Department"] == "finance"
print (df["Department"])

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
Name: Department, dtype: bool

In [ ]:
import pandas as pd
df = pd.read_csv("employee_data_raw.csv")

df["possibility1"] = df["City"] == "Karachi"
df["possibility2"] = df["Salary"] >= 60000
df["final_result"] = df["possibility1"] & df["possibility2"]
karachi_high_salary_employees = df[df["final_result"]]
display(karachi_high_salary_employees)

,Employee_ID,Employee_Name,City,Department,Salary,Joining_Year,possibility1,possibility2,final_result
0,1001,ali khan,Karachi,Finance,70000,2018,True,True,True
3,1010,Hira Shah,Karachi,operations,65000,2017,True,True,True
4,1017,Saad Hassan,Karachi,Marketing,75000,2023,True,True,True
6,1025,Rehan Ahmed,Karachi,IT,80000,2017,True,True,True
7,1026,Anum Tariq,Karachi,it,75000,2024,True,True,True

In [ ]:
import pandas as pd
df = pd.read_csv("employee_data_raw.csv")
df_sorted_salary = df.sort_values("Salary")
print(df_sorted_salary)

   Employee_ID  Employee_Name     City    Department  Salary  Joining_Year
1         1002     Sara Ahmed  Karachi       finance   42000          2021
2         1009    Bilal Ahmed  Karachi    Operations   50000          2025
5         1018      Maha Khan  Karachi     marketing   55000          2021
8         1018      Maha Khan  Karachi     marketing   55000          2021
3         1010      Hira Shah  Karachi   operations    65000          2017
0         1001      ali khan   Karachi       Finance   70000          2018
7         1026     Anum Tariq  Karachi            it   75000          2024
4         1017    Saad Hassan  Karachi     Marketing   75000          2023
6         1025    Rehan Ahmed  Karachi            IT   80000          2017

In [ ]:

df["Salary_Category"] = df["Salary"].apply(
     lambda x: "High" if x >= 60000 else "Medium" if x >= 50000 else "Low"
     )

print(df["Salary"])

0    70000
1    42000
2    50000
3    65000
4    75000
5    55000
6    80000
7    75000
8    55000
Name: Salary, dtype: int64

In [17]:
#print(max(marks))               #highestmarks
#print(min(marks))               #lowestmarks
#print(sum(marks)/len(marks))     #avgeragemarks
#print(sum(marks))                #totalmarks

import pandas as pd
df = pd.read_csv("employee_data_raw.csv")
df.groupby("Department")["Salary"].mean()
print(df)

    Employee_ID   Employee_Name         City    Department  Salary  \
0          1001       ali khan       Karachi       Finance   70000
1          1002      Sara Ahmed     karachi        finance   42000
2          1003       ahmed ali       LAHORE            HR   50000
3          1004     Ayesha Khan      lahore            hr    48000
4          1005    Hassan Raza     Islamabad            IT   70000
5          1006     fatima Noor    ISLAMABAD            it   45000
6          1007     Usman Tariq   Rawalpindi     Marketing   42000
7          1008    zainab malik  rawalpindi      marketing   45000
8          1009     Bilal Ahmed      Karachi    Operations   50000
9          1010       Hira Shah     karachi    operations    65000
10         1011     Omar Farooq       LAHORE       Finance   62000
11         1012      sana iqbal      lahore        finance   75000
12         1013      Hamza Khan    Islamabad            HR   58000
13         1014      Maryam Ali    ISLAMABAD           hr    60000
14         1015     Danish Raza   Rawalpindi            IT   80000
15         1016      Iqra Ahmed  rawalpindi             it   80000
16         1017     Saad Hassan      Karachi     Marketing   75000
17         1018       Maha Khan     karachi      marketing   55000
18         1019     Talha Malik       LAHORE    Operations   48000
19         1020      Nimra Shah      lahore    operations    80000
20         1021       Fahad Ali    Islamabad       Finance   45000
21         1022      Komal Raza    ISLAMABAD       finance   58000
22         1023       Asad Khan   Rawalpindi            HR   55000
23         1024      Laiba Noor  rawalpindi            hr    65000
24         1025     Rehan Ahmed      Karachi            IT   80000
25         1026      Anum Tariq     karachi             it   75000
26         1027   Shahzaib Khan       LAHORE     Marketing   62000
27         1028        Eman Ali      lahore      marketing   58000
28         1029      Arham Raza    Islamabad    Operations   62000
29         1030    Areeba Malik    ISLAMABAD   operations    70000
30         1006     fatima Noor    ISLAMABAD            it   45000
31         1018       Maha Khan     karachi      marketing   55000

    Joining_Year
0           2018
1           2021
2           2020
3           2018
4           2025
5           2023
6           2017
7           2020
8           2025
9           2017
10          2020
11          2025
12          2020
13          2021
14          2017
15          2019
16          2023
17          2021
18          2020
19          2022
20          2018
21          2018
22          2022
23          2021
24          2017
25          2024
26          2018
27          2018
28          2021
29          2022
30          2023
31          2021

In [22]:
import pandas as pd
df = pd.read_csv("employee_data_raw.csv")
df.groupby("City")["Salary"].sum('Salary')
print(df.head())

   Employee_ID Employee_Name       City Department  Salary  Joining_Year
0         1001     ali khan     Karachi    Finance   70000          2018
1         1002    Sara Ahmed   karachi     finance   42000          2021
2         1003     ahmed ali     LAHORE         HR   50000          2020
3         1004   Ayesha Khan    lahore         hr    48000          2018
4         1005  Hassan Raza   Islamabad         IT   70000          2025

In [23]:
import pandas as pd
df = pd.read_csv("employee_data_raw.csv")
df_count=df.groupby("Department")["Employee_ID"].count()
print(df_count.head())

Department
 hr             3
 operations     3
Finance         3
HR              3
IT              3
Name: Employee_ID, dtype: int64

In [2]:
highest_avg_salary = df_high_avg.max()
department_with_highest_avg_salary = df_high_avg.idxmax()

print(f"The highest average salary is: {highest_avg_salary:.2f}")
print(f"This belongs to the department: {department_with_highest_avg_salary}")

NameError: name 'df_high_avg' is not defined

In [3]:
import pandas as pd
import os

file_path = "employee_data_raw.csv"

if not os.path.exists(file_path):
    print(f"Error: The file '{file_path}' was not found. Please upload it to your Colab environment to get meaningful results.")
    df = pd.DataFrame() # Create an empty DataFrame to prevent further errors
else:
    df = pd.read_csv(file_path)

# Standardize Department names for consistent grouping
if not df.empty:
    df["Department"] = df["Department"].str.strip().str.title()
    df_high_avg = df.groupby("Department")["Salary"].mean()

    highest_avg_salary = df_high_avg.max()
    department_with_highest_avg_salary = df_high_avg.idxmax()

    print(f"The highest average salary is: {highest_avg_salary:.2f}")
    print(f"This belongs to the department: {department_with_highest_avg_salary}")
else:
    print("Cannot calculate highest average salary: DataFrame is empty.")

FileNotFoundError: [Errno 2] No such file or directory: 'employee_data_raw.csv'

In [30]:
import pandas as pd
df = pd.read_csv("employee_data_raw.csv")
df_emp=df.groupby("Employee_ID")["Salary"].mean()
print(f"The  average salary of all employees are: {df_emp}")

The  average salary of all employees are: Employee_ID
1001    70000.0
1002    42000.0
1003    50000.0
1004    48000.0
1005    70000.0
1006    45000.0
1007    42000.0
1008    45000.0
1009    50000.0
1010    65000.0
1011    62000.0
1012    75000.0
1013    58000.0
1014    60000.0
1015    80000.0
1016    80000.0
1017    75000.0
1018    55000.0
1019    48000.0
1020    80000.0
1021    45000.0
1022    58000.0
1023    55000.0
1024    65000.0
1025    80000.0
1026    75000.0
1027    62000.0
1028    58000.0
1029    62000.0
1030    70000.0
Name: Salary, dtype: float64

##highest tootal  salary expenditure

In [5]:
import pandas as pd
import os

file_path = "employee_data_raw.csv"

if not os.path.exists(file_path):
    print(f"Error: The file '{file_path}' was not found. Please upload it to your Colab environment to get meaningful results.")
    df = pd.DataFrame() # Create an empty DataFrame to prevent further errors
else:
    df = pd.read_csv(file_path)

# Standardize Department names for consistent grouping
if not df.empty:
    df["Department"] = df["Department"].str.strip().str.title()
    df_total_salary_per_department = df.groupby("Department")["Salary"].sum()

    highest_total_expenditure = df_total_salary_per_department.max()
    department_with_highest_total_expenditure = df_total_salary_per_department.idxmax()

    print(f"The highest total salary expenditure is: {highest_total_expenditure:.2f}")
    print(f"This belongs to the department: {department_with_highest_total_expenditure}")
else:
    print("Cannot calculate highest total salary expenditure: DataFrame is empty.")

The highest total salary expenditure is: 475000.00
This belongs to the department: It